### PR TITLE
Issue #37 resolution: New Reaction Workflows

### LINKED ISSUE #37: Support Reaction with Message#reacted_with
A common flow could be to get all users who reacted on a message.

```rb
message = ... # Could be event.message or message.channel(c_id).load_message(m_id)
all_reactions = message.reactions.each_with_object({}) { |r, h| h[r.to_s] = message.reacted_with(r) }
```

Currently, this gives
```rb
Traceback (most recent call last):
        5: from /.../discordrb/data/message.rb:284:in `reacted_with'
        4: from /.../discordrb/data/message.rb:284:in `to_a'
        3: from /.../discordrb/paginator.rb:28:in `each'
        2: from /.../discordrb/data/message.rb:281:in `block in reacted_with'
        1: from /.../discordrb/api/channel.rb:203:in `get_reactions'
NoMethodError (undefined method `ascii_only?' for #<Discordrb::Reaction:0x0000000002a50fa8>)
```

and can be solved by doing `message.reacted_with(r.to_s)` but we already support Emoji, so why not Reaction for consistency?

Further, we could provide this flow as a method such as `Message#all_reaction_users`. I'd put a warning on it that it needs to paginate for every 100 reactions though.

### PR DESCRIPTION
**Pull request by TheMesp**
# Summary

Making my discord bot obtain a list of users who reacted to a message was a bit unintuitive at first. Then I noticed the open issue #37 related to adding new functionality to reactions and decided to tackle this issue so that my bots and others like it can take advantage of the new workflows. 

#  Example Workflows:

Lets say you're hosting a giveaway and want people to enter for different prize pools 🟥 and 🟢 based on their reaction:
`giveaway_message.all_reaction_users`
`=> { '🟥' => [<User bob>, <User jack>], '🟢' => [<User bob>, <User jane>] }`

Additionally, it is no longer required to resolve a reaction to a string to use it with `Message#reacted_with`:
`giveaway_message.reacted_with(<Reaction 🟥>, limit:100)`
`=> [<User bob>, <User jack>]`

Resolves #37 

---

## Added

- Implemented `Message#all_reaction_users` which returns a hash of reactions and users who used it
- Added rspec tests for additions and changed features

## Changed

- added to_s coercion for reaction argument in `Message#reacted_with`

### CODE REVIEW

File: lib/discordrb/data/message.rb [hunk 1]
```diff
@@ -304,6 +305,16 @@ def reacted_with(reaction, limit: 100)
       paginator.to_a
     end
 
+    # Returns a hash of all reactions to a message as keys and the users that reacted to it as values.
+    # @param limit [Integer] the limit of how many users to retrieve per distinct reaction emoji. `nil` will return all users
+    # @example Get all the users that reacted to a message for a giveaway.
+    #   giveaway_participants = message.all_reaction_users
+    # @return {String => [Array<User>]} a hash with key=reaction.to_s, value=[Array<User>]
```
Comment (swarley) [inline lib/discordrb/data/message.rb]:
```suggestion
    # @return [Hash<String => Array<User>>] A hash mapping the string representation of a
    #   reaction to an array of users.
```

**Comment by swarley** [comment]
Thanks!
