### PR TITLE
Don't send an empty limit query parameter for Channel#get_channel

### LINKED ISSUE #38: Bug: Message#reacted_with limit: nil gives a 400
```rb
bot.channel(c_id).load_message(m_id).reacted_with(emoji, limit: nil)
```

```rb
Traceback (most recent call last):
       16: from /.../discordrb/data/message.rb:284:in `reacted_with'
       15: from /.../discordrb/data/message.rb:284:in `to_a'
       14: from /.../discordrb/paginator.rb:28:in `each'
       13: from /.../discordrb/data/message.rb:281:in `block in reacted_with'
       12: from /.../discordrb/api/channel.rb:205:in `get_reactions'
       11: from /.../discordrb/api.rb:115:in `request'
       10: from /.../discordrb/api.rb:81:in `raw_request'
        9: from /.../restclient.rb:66:in `get'
        8: from /.../restclient/request.rb:63:in `execute'
        7: from /.../restclient/request.rb:163:in `execute'
        6: from /.../restclient/request.rb:727:in `transmit'
        5: from /.../ruby/2.7.0/net/http.rb:933:in `start'
        4: from /.../restclient/request.rb:743:in `block in transmit'
        3: from /.../restclient/request.rb:836:in `process_result'
        2: from /.../restclient/abstract_response.rb:129:in `return!'
        1: from /.../restclient/abstract_response.rb:249:in `exception_with_response'
RestClient::BadRequest (400 Bad Request)
```

Unsure if this is a problem with the Paginator or something else

### PR DESCRIPTION
**Pull request by kaine119**
# Summary
Fixes #38.  
Discord tries to parse the `limit` parameter as an integer, if nothing is sent a HTTP 400 is returned. This sets a default to the maximum instead of the usual 25, to reduce the number of requests needed to get all users when `limit: nil` is passed.

---

## Added
Specs for `Message#reacted_with` and `API::Channel.get_reactions`

## Changed
* API::Channel.get_reactions: the query param `limit` defaults to 100 instead of the empty string when limit is nil.

### CODE REVIEW

**Comment by Daniel-Worrall** [comment]
Been talking about this one in the discord before submission.
LGTM, would love some specs, and let's get CI before any merge

File: lib/discordrb/api/channel.rb [hunk 1]
```diff
@@ -201,7 +201,7 @@ def delete_user_reaction(token, channel_id, message_id, emoji, user_id)
   # https://discord.com/developers/docs/resources/channel#get-reactions
   def get_reactions(token, channel_id, message_id, emoji, before_id, after_id, limit = 100)
     emoji = URI.encode_www_form_component(emoji) unless emoji.ascii_only?
-    query_string = "limit=#{limit}#{"&before=#{before_id}" if before_id}#{"&after=#{after_id}" if after_id}"
+    query_string = "limit=#{limit || 100}#{"&before=#{before_id}" if before_id}#{"&after=#{after_id}" if after_id}"
```
Comment (swarley) [inline lib/discordrb/api/channel.rb]: I would prefer to see this as

```ruby
query_string = URI.encode_www_form({ limit: limit, before: before_id, after: after_id }.compact)
```

File: spec/api/channel_spec.rb [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+  describe '.get_reactions' do
+    let(:message_id) { double('message_id') }
+    let(:before_id) { double('before_id') }
+    let(:after_id) { double('after_id') }
+
+    before do
+      allow(message_id).to receive(:to_s).and_return('message_id')
+      allow(before_id).to receive(:to_s).and_return('before_id')
+      allow(after_id).to receive(:to_s).and_return('after_id')
+
```
Comment (Daniel-Worrall) [inline spec/api/channel_spec.rb]: and here
```suggestion
    let(:message_id) { double('message_id', to_s: 'message_id') }
    let(:before_id) { double('before_id', to_s: 'before_id') }
    let(:after_id) { double('after_id', to_s: 'after_id') }

    before
```

File: spec/api/channel_spec.rb [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+require 'discordrb'
+
+describe Discordrb::API::Channel do
+  let(:token) { double('token') }
+  let(:channel_id) { instance_double(String, 'channel_id') }
+
+  before do
+    allow(token).to receive(:to_s).and_return('bot_token')
+    allow(channel_id).to receive(:to_s).and_return('channel_id')
+  end
```
Comment (Daniel-Worrall) [inline spec/api/channel_spec.rb]: We can move these method stubs inside the double initialiser
```suggestion
  let(:token) { double('token', to_s: 'bot_token') }
  let(:channel_id) { instance_double(String, 'channel_id', to_s: 'channel_id') }
```

File: spec/api/channel_spec.rb [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+      allow(before_id).to receive(:to_s).and_return('before_id')
+      allow(after_id).to receive(:to_s).and_return('after_id')
+
+      allow(Discordrb::API).to receive(:request)
+        .with(anything, channel_id, :get, kind_of(String), any_args)
+    end
+
+    it 'sends requests' do
+      Discordrb::API::Channel.get_reactions(token, channel_id, message_id, 'test', before_id, after_id, 27)
+      expect(Discordrb::API).to have_received(:request)
```
Comment (Daniel-Worrall) [inline spec/api/channel_spec.rb]: while `have_received` is valid spec'ing known as using spies, I'd prefer we stay consistent and put the expectations before the call

File: spec/api/channel_spec.rb [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+          channel_id,
+          :get,
+          "#{Discordrb::API.api_base}/channels/#{channel_id}/messages/#{message_id}/reactions/test?limit=27&before=#{before_id}&after=#{after_id}",
+          any_args
+        )
+    end
+
+    it 'percent-encodes emoji' do
+      Discordrb::API::Channel.get_reactions(token, channel_id, message_id, "\u{1F44D}", before_id, after_id, 27)
+      expect(Discordrb::API).to have_received(:request)
```
Comment (Daniel-Worrall) [inline spec/api/channel_spec.rb]: same here

File: spec/api/channel_spec.rb [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+          channel_id,
+          :get,
+          "#{Discordrb::API.api_base}/channels/#{channel_id}/messages/#{message_id}/reactions/%F0%9F%91%8D?limit=27&before=#{before_id}&after=#{after_id}",
+          any_args
+        )
+    end
+
+    it 'uses the maximum limit of 100 if nil is provided' do
+      Discordrb::API::Channel.get_reactions(token, channel_id, message_id, 'test', before_id, after_id, nil)
+      expect(Discordrb::API).to have_received(:request)
```
Comment (Daniel-Worrall) [inline spec/api/channel_spec.rb]: and here

File: spec/data/message_spec.rb [hunk 7]
```diff
@@ -109,6 +109,53 @@
...
+
+      allow(Discordrb::API::Channel).to receive(:get_reactions)
+        .with(any_args, user_data['id'].to_i, anything)
+        .and_return([].to_json)
+    end
+
+    it 'calls the API method' do
+      message.reacted_with('\u{1F44D}', limit: 27)
+
+      expect(Discordrb::API::Channel).to have_received(:get_reactions)
```
Comment (Daniel-Worrall) [inline spec/data/message_spec.rb]: and here

File: spec/data/message_spec.rb [hunk 8]
```diff
@@ -109,6 +109,53 @@
...
+        .with(any_args, '\u{1F44D}', nil, nil, 27)
+    end
+
+    it 'defaults to a limit of 100' do
+      message.reacted_with('\u{1F44D}')
+
+      expect(Discordrb::API::Channel).to have_received(:get_reactions)
```
Comment (Daniel-Worrall) [inline spec/data/message_spec.rb]: ditto

File: spec/data/message_spec.rb [hunk 9]
```diff
@@ -109,6 +109,53 @@
...
+
+      message.reacted_with('\u{1F44D}', limit: nil)
+    end
+
+    it 'converts Emoji to strings' do
+      allow(emoji).to receive(:to_reaction).and_return('123')
+
+      message.reacted_with(emoji)
+
+      expect(Discordrb::API::Channel).to have_received(:get_reactions)
```
Comment (Daniel-Worrall) [inline spec/data/message_spec.rb]: ditto

**Review by Daniel-Worrall — CHANGES_REQUESTED** [review]
lgtm so far. Just some nitpicky spec changes going forward. I'm aware some parts of the library also use these things I've criticised which is where you may have taken inspiration from, but it's on the agenda to go over the specs to make them more consistent, and document guidelines in a Contributing section

**Review by Daniel-Worrall — APPROVED** [review]
lgtm.

Was gonna say "let's see about CI" but it seems to be working now :)

File: lib/discordrb/api/channel.rb [hunk 10]
```diff
@@ -201,7 +201,7 @@ def delete_user_reaction(token, channel_id, message_id, emoji, user_id)
   # https://discord.com/developers/docs/resources/channel#get-reactions
   def get_reactions(token, channel_id, message_id, emoji, before_id, after_id, limit = 100)
     emoji = URI.encode_www_form_component(emoji) unless emoji.ascii_only?
-    query_string = "limit=#{limit}#{"&before=#{before_id}" if before_id}#{"&after=#{after_id}" if after_id}"
+    query_string = URI.encode_www_form({ limit: limit || 100, before: before_id, after: after_id }.compact)
```
Comment (swarley) [inline lib/discordrb/api/channel.rb:204]: Could we possibly drop the `|| 100` here? It's redundant with the default value from the method signature.

**Review by swarley — CHANGES_REQUESTED** [review]
Just one small fix and then things should be good to go!

File: lib/discordrb/api/channel.rb (hunk 10 above)
Comment (Daniel-Worrall) [reply lib/discordrb/api/channel.rb:204]: From the original bug report #38, `Message#reacted_with` will pass nil to the paginator (and therefore the API method) to get all results. The default return amount from the API is 25, so specifying 100 (aka max) will reduce the amount of API requests we need to make to get all results.

**Review by swarley — APPROVED** [review]

**Comment by swarley** [comment]
Thank you!
